spring.application.name=tarefasgerenciamento
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefas_db
spring.datasource.username=seu_usuario (normalmente usas se 'postgres')
spring.datasource.password=sua_senha_do_bd
spring.datasource.driver-class-name=org.postgresql.Driver